version: 0.2
env:
  variables:
    APP_NAME: "mern-frontend-pipeline"
phases:
  install:
    runtime-versions:
      nodejs: 16.13.1
    commands:
      - echo install process started
      - yarn
  build:
    commands:
      - echo build process started now
      - yarn build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://dailyshop.buys.ninja --delete
