version: 1.0
env:
  variables:
    APP_NAME: "dailyshop.buys.ninja"
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo install process started
      - yarn
  build:
    commands:
      - echo build process started now
      - yarn build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd build/
      - ls -la
      - aws s3 sync . s3://dailyshop.buys.ninja --delete
